version: '3'
services:
  backend:
    container_name: backend-chat-app
    image: tuananh2582000/zahoo-backend:v12
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - "5000:5000"
    environment:
      MONGO_URL: mongodb+srv://adminta:4cOXO9QbEGA4iYEK@cluster0.jalmg.mongodb.net/test?retryWrites=true&w=majority
      PORT: 5000
      PEER_PORT: 3001
      PEER_PATH: /
      TOKEN_SECRET_KEY: 123
      TOKEN_REFRESH_SECRET_KEY: 123456
      AWS_ACCESS_KEY_ID: AKIATP6WCE76BNTO2DPO
      AWS_SECRET_ACCESS_KEY: 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
      AWS_REGION: ap-southeast-1
      AWS_BUCKET_NAME: chat-app-s3
    networks:
      - common
    volumes:  
      - ./server:/app
      - /app/node_modules
  frontend:
    stdin_open: true
    tty: true
    container_name: frontend-chat-app
    image: tuananh2582000/zahoo-frontend:v12
    build:
      context: ./client
      dockerfile: Dockerfile.prod
      args:
        REACT_APP_PEER_PORT: 3001
        REACT_APP_PEER_PATH: /
        REACT_APP_BASE_URL: http://localhost:5000
    ports:
      - "80:80"
      - "443:443"
    networks:
      - common
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend
    links:
      - backend
networks:
  common:
    driver: bridge