export const GLOBALTYPES = {
  AUTH: "AUTH",
  REGISTER: "REGISTER",
  ALERT: "ALERT",
  SOCKET: "SOCKET",
  ONLINE: "ONLINE",
  OFFLINE: "OFFLINE",
  CALL: "CALL",
  PEER: "PEER",
  GET_CONVERSATIONS_SUCCESS: "GET_CONVERSATIONS_SUCCESS",
  GET_IMAGE_VIDEO: "GET_IMAGE_VIDEO",
  GET_FILES: "GET_FILES",
  POST_CONVERSATION: "POST_CONVERSATION",
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  GET_USER_REQUEST: "GET_USER_REQUEST",
  GET_USER_ERR: "GET_USER_ERR",
  POST_CURRENT_CONVERSATION_SUCCESS: "POST_CURRENT_CONVERSATION_SUCCESS",
  GET_MESSAGES_SUCCESS: "GET_MESSAGES_SUCCESS",
  UPDATE_MESSAGES: "UPDATE_MESSAGES",
  ADD_MESSAGE: "ADD_MESSAGE",
  UPDATE_LAST_MSG: "UPDATE_LAST_MSG",
  UPDATE_COUNT_WAITING_MESSAGE: "UPDATE_COUNT_WAITING_MESSAGE",
  REMOVE_COUNT_WAITING_MESSAGE: "REMOVE_COUNT_WAITING_MESSAGE",
  SHOW_ADDFRIEND_MODAL: "SHOW_ADDFRIEND_MODAL",
  SHOW_ADDGROUP_MODAL: "SHOW_ADDGROUP_MODAL",
  SHOW_CHANGE_GROUP_NAME_MODAL: "SHOW_CHANGE_GROUP_NAME_MODAL",
  CHANGE_GROUP_NAME_OF_CURRENT_CONVERSATION:
    "CHANGE_GROUP_NAME_OF_CURRENT_CONVERSATION",
  CHANGE_GROUP_NAME_OF_CONVERSATION_IN_LIST_CONVERSATION:
    "CHANGE_GROUP_NAME_OF_CONVERSATION_IN_LIST_CONVERSATION",

  TOGGLE_MORE_INFO_CONVERSATION: "TOGGLE_MORE_INFO_CONVERSATION",
  HIDE_MODAL: "HIDE_MODAL",
  REMOVE_USER_SUCCESS: "REMOVE_USER_SUCCESS",
  REQUEST_ADD_FRIEND: "REQUEST_ADD_FRIEND",
  CANCEL_ADD_FRIEND: "CANCEL_ADD_FRIEND",
  ACCEPT_ADD_FRIEND: "ACCEPT_ADD_FRIEND",
  DENIED_ADD_FRIEND: "DENIED_ADD_FRIEND",
  UPDATE_FRIENDS_QUEUE: "UPDATE_FRIENDS_QUEUE",
  UPDATE_FRIENDS: "UPDATE_FRIENDS",

  GET_ALL_USERS: "GET_ALL_USERS",
  ACTIVE_USER: "ACTIVE_USER",

  NOTIFY: "NOTIFY",
  CLOSE_NOTIFY: "CLOSE_NOTIFY",
  UPDATE_SOUND: "UPDATE_SOUND",

  TYPING_TEXT: "TYPING_TEXT",
  OFF_TYPING_TEXT: "OFF_TYPING_TEXT",
  SUGGESS_FRIENDS: "SUGGESS_FRIENDS",
  OUT_GROUP_TO_CLIENT:"OUT_GROUP_TO_CLIENT",
  OUT_GROUP:"OUT_GROUP",
  DELETE_GROUP:"DELETE_GROUP",
  DELETE_GROUP_TO_CLIENT:"DELETE_GROUP_TO_CLIENT",
  SHOW_ADD_FRIEND_TO_GROUP_MODAL:"SHOW_ADD_FRIEND_TO_GROUP_MODAL",
  UPDATE_CURRENT_CONVERSATION_ADD_MEMBER:"UPDATE_CURRENT_CONVERSATION_ADD_MEMBER",
  UPDATE_CONVERSATIONS_ADD_MEMBER:"UPDATE_CONVERSATIONS_ADD_MEMBER",
  ADD_MEMBER_GROUP_TO_CLIENT:"ADD_MEMBER_GROUP_TO_CLIENT",

 ACTIVE_USER_TO_CLIENT:"ACTIVE_USER_TO_CLIENT"



};
