version: "3"
services:
  backend:
    image: tuananh2582000/zahoo-nodejs
    ports:
      - "5000:5000"
    environment:
      MONGO_URL: mongodb+srv://adminta:4cOXO9QbEGA4iYEK@cluster0.jalmg.mongodb.net/test?retryWrites=true&w=majority
      PORT: 5000
      PEER_PORT: 3001
      PEER_PATH: /
      TOKEN_SECRET_KEY: 123
      TOKEN_REFRESH_SECRET_KEY: 123456
      AWS_ACCESS_KEY_ID: AKIATP6WCE76BNTO2DPO
      AWS_SECRET_ACCESS_KEY: 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
      AWS_REGION: ap-southeast-1
      AWS_BUCKET_NAME: chat-app-s3
    networks:
      - common
    # volumes:
    #   - ./server:/app
    #   - /app/node_modules
  frontend:
    stdin_open: true
    tty: true
    image: tuananh2582000/zahoo-reactjs
    ports:
      - "80:80"
      - "443:443"
    networks:
      - common
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./key-ssl:/etc/nginx/ssl/live/zahoo.xyz
      # - ./client:/app
      # - /app/node_modules
    depends_on:
      - backend
networks:
  common:
    driver: bridge
